name = input("Введите ваше имя:")
surname = input("Введите вашу фамилию:")
favorite_animal = input("Ваше любимое животное:")
sign = input("Ваш знак зодиака:")
print("Индивидуальный гороскоп для пользователя {} {}".format(name, surname))
print("Кем вы были в прошлой жизни: {}".format(favorite_animal))
print("Ваш знак зодиака - {} , поэтому вы - тонко чувствующая натура.".format(sign))